name: SGT Build Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment (e.g., Production, Staging)"
        required: true
        default: "Production"
        type: string
      run_build:
        description: "Run build step"
        required: true
        default: true
        type: boolean
      run_tests:
        description: "Run tests"
        required: true
        default: false
        type: boolean
      run_sonarqube:
        description: "Run SonarQube analysis"
        required: true
        default: false
        type: boolean
      run_blackduck:
        description: "Run BlackDuck security scan"
        required: true
        default: false
        type: boolean
      upload_to_store:
        description: "Upload build to the App Store"
        required: true
        default: false
        type: boolean
      what_to_test_text:
        description: "TestFlight information"
        required: false
        type: string

permissions:
  contents: write
  actions: write

env:
  BUILD_NUMBER_BASE: 200
  CONFIGURATION: Release
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_VERSION: 8.x
  OUTPUT_FOLDER: ${{ github.workspace }}/output
  RUN_NUMBER: ${{ github.run_number }}
  XCODE_VERSION: 15.4

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 🚀 Notify Slack - Build Started
      - name: Get commit message
        run: |
          echo "COMMIT_MESSAGES<<EOF" >> $GITHUB_ENV
          git log -1 --pretty=%B >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Notify Slack - Build Started
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: >
            {
              "text": "🚀 Build started for *${{ github.repository }}* Triggered by *${{ github.actor }}*"",
              "attachments": [
                {
                  "color": "#3498db",
                  "fields": [
                    { "title": "Branch", "value": "${{ github.ref }}", "short": true },
                    { "title": "Commit SHA", "value": "${{ github.sha }}", "short": true },
                    { "title": "Triggered by", "value": "${{ github.actor }}", "short": true }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Measure Start Time
        run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV

      - name: Print inputs
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Run Build: ${{ github.event.inputs.run_build }}"
          echo "Run Tests: ${{ github.event.inputs.run_tests }}"
          echo "Run SonarQube: ${{ github.event.inputs.run_sonarqube }}"
          echo "Run BlackDuck: ${{ github.event.inputs.run_blackduck }}"
          echo "Upload to Store: ${{ github.event.inputs.upload_to_store }}"
          echo "What To Test Text: ${{ github.event.inputs.what_to_test_text }}"

      - name: Set What To Test Text
        run: |
          echo "WHAT_TO_TEST_TEXT=Environment: ${{ github.event.inputs.environment }}\nBranch: $(git rev-parse --abbrev-ref HEAD)\nSHA: $(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Select Xcode version
        run: sudo xcode-select -switch /Applications/Xcode_${{ env.XCODE_VERSION }}.app

      - name: Increase version number
        run: |
          for PLIST_FILE in $(find . -name "Info*.plist" -type f -not -path '*/bin/*' -not -path '*/obj/*')
          do
            echo "Updating build number in ${PLIST_FILE}"
            plutil -replace CFBundleVersion -string $((${{ env.BUILD_NUMBER_BASE }} + ${{ env.RUN_NUMBER }})) "${PLIST_FILE}"
          done

      - name: Run BlackDuck scan
        if: github.event.inputs.run_blackduck == 'true'
        run: echo "Running BlackDuck scan..."

      - name: Run Tests
        if: github.event.inputs.run_tests == 'true'
        run: dotnet test --filter FullyQualifiedName~Tests

      - name: Run SonarQube
        if: github.event.inputs.run_sonarqube == 'true'
        run: echo "Running SonarQube analysis..."

      - name: Build app
        if: github.event.inputs.run_build == 'true'
        env:
          IOS_CODESIGNING_IDENTITY_NAME: ${{ vars.IOS_CODESIGNING_IDENTITY_NAME }}
          IOS_CODESIGNING_PROVISIONING_PROFILE_NAME: ${{ vars.IOS_CODESIGNING_PROVISIONING_PROFILE_NAME }}
          IOS_CODESIGNING_PROVISIONING_PROFILE_NOTIFICATION_NAME: ${{ vars.IOS_CODESIGNING_PROVISIONING_PROFILE_NOTIFICATION_NAME }}
        run: >
          dotnet build
          -c "${{ env.CONFIGURATION }}"
          -t:"${{ env.PROJECT_NAME_IOS }}"
          -p:Platform="iPhone"
          -p:RuntimeIdentifier="ios-arm64"
          -p:BuildIpa=true
          ${{ env.SOLUTION_FILE }}

      - name: Upload app artifacts
        if: github.event.inputs.upload_to_store == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: ios
          path: ${{ env.PROJECT_FOLDER_IOS }}/bin/iPhone/${{ env.CONFIGURATION }}/net*-ios/ios-arm64/*.ipa
          retention-days: 3

      - name: Upload app symbols
        if: github.event.inputs.upload_to_store == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: ios-dsym
          path: ${{ env.PROJECT_FOLDER_IOS }}/bin/iPhone/${{ env.CONFIGURATION }}/net*-ios/ios-arm64/*.dSYM
          retention-days: 3

      # 🟢 Notify Slack - Build Success
      - name: Measure End Time
        run: echo "END_TIME=$(date +%s)" >> $GITHUB_ENV

      - name: Calculate Execution Time
        run: |
          EXEC_TIME=$((END_TIME - START_TIME))
          echo "EXECUTION_TIME=${EXEC_TIME}" >> $GITHUB_ENV

      - name: Notify Slack - Build Success
        if: success()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: >
            {
              "text": "✅ Build Succeeded for *${{ github.repository }}*, Version *${{ github.BUILD_NUMBER }}*, Execution Time *${{ github.EXECUTION_TIME }}*",
              "attachments": [
                {
                  "color": "#2ecc71",
                  "fields": [
                    { "title": "Branch", "value": "${{ github.ref }}", "short": true },
                    { "title": "Commit SHA", "value": "${{ github.sha }}", "short": true },
                    { "title": "Version", "value": "${{ env.BUILD_NUMBER }}", "short": true },
                    { "title": "Execution Time", "value": "${{ env.EXECUTION_TIME }}s", "short": true }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      # 🔴 Notify Slack - Build Failed
      - name: Notify Slack - Build Failed
        if: failure()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: >
            {
              "text": "❌ Build Failed for *${{ github.repository }}*, Execution Time *${{ github.EXECUTION_TIME }}*",
              "attachments": [
                {
                  "color": "#e74c3c",
                  "fields": [
                    { "title": "Branch", "value": "${{ github.ref }}", "short": true },
                    { "title": "Commit SHA", "value": "${{ github.sha }}", "short": true },
                    { "title": "Triggered by", "value": "${{ github.actor }}", "short": true },
                    { "title": "Error", "value": "See logs for details", "short": false },
                    { "title": "Execution Time", "value": "${{ env.EXECUTION_TIME }}s", "short": true }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
