name: Slack Notifications

on:
  repository_dispatch:
    types: [build-completed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: "GitHub Actions"
          SLACK_ICON_EMOJI: ":rocket:"
          SLACK_MESSAGE: "Build Status: *${{ github.event.client_payload.status }}*\nBranch: *${{ github.event.client_payload.branch }}*\nRepository: *${{ github.event.client_payload.repo }}*\nTriggered by: *${{ github.event.client_payload.actor }}*"
